ALTER TABLE "AuditLog"
DROP CONSTRAINT "AuditLog_tenantId_fkey";

ALTER TABLE "AuditLog"
ADD CONSTRAINT "AuditLog_tenantId_fkey"
FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id")
ON DELETE CASCADE ON UPDATE CASCADE;
