/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAuditRouteImport } from './routes/_protected/audit'
import { Route as ProtectedFlagsRouteImport } from './routes/_protected/flags'
import { Route as ProtectedServicesRouteImport } from './routes/_protected/services'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSubscriptionsRouteImport } from './routes/_protected/subscriptions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ProtectedTenantsIndexRouteImport } from './routes/_protected/tenants/index'
import { Route as ProtectedTenantsIdRouteImport } from './routes/_protected/tenants/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiV1EntitlementsTenantIdRouteImport } from './routes/api/v1/entitlements/$tenantId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditRoute = ProtectedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFlagsRoute = ProtectedFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesRoute = ProtectedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSubscriptionsRoute = ProtectedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTenantsIndexRoute = ProtectedTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTenantsIdRoute = ProtectedTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntitlementsTenantIdRoute =
  ApiV1EntitlementsTenantIdRouteImport.update({
    id: '/api/v1/entitlements/$tenantId',
    path: '/api/v1/entitlements/$tenantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof ProtectedAuditRoute
  '/flags': typeof ProtectedFlagsRoute
  '/services': typeof ProtectedServicesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/subscriptions': typeof ProtectedSubscriptionsRoute
  '/api/health': typeof ApiHealthRoute
  '/tenants/$id': typeof ProtectedTenantsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/tenants/': typeof ProtectedTenantsIndexRoute
  '/api/v1/entitlements/$tenantId': typeof ApiV1EntitlementsTenantIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof ProtectedAuditRoute
  '/flags': typeof ProtectedFlagsRoute
  '/services': typeof ProtectedServicesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/subscriptions': typeof ProtectedSubscriptionsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof ProtectedIndexRoute
  '/tenants/$id': typeof ProtectedTenantsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/tenants': typeof ProtectedTenantsIndexRoute
  '/api/v1/entitlements/$tenantId': typeof ApiV1EntitlementsTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/audit': typeof ProtectedAuditRoute
  '/_protected/flags': typeof ProtectedFlagsRoute
  '/_protected/services': typeof ProtectedServicesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/subscriptions': typeof ProtectedSubscriptionsRoute
  '/api/health': typeof ApiHealthRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/tenants/$id': typeof ProtectedTenantsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_protected/tenants/': typeof ProtectedTenantsIndexRoute
  '/api/v1/entitlements/$tenantId': typeof ApiV1EntitlementsTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/flags'
    | '/services'
    | '/settings'
    | '/subscriptions'
    | '/api/health'
    | '/tenants/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/tenants/'
    | '/api/v1/entitlements/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/flags'
    | '/services'
    | '/settings'
    | '/subscriptions'
    | '/api/health'
    | '/'
    | '/tenants/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/tenants'
    | '/api/v1/entitlements/$tenantId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/audit'
    | '/_protected/flags'
    | '/_protected/services'
    | '/_protected/settings'
    | '/_protected/subscriptions'
    | '/api/health'
    | '/_protected/'
    | '/_protected/tenants/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/_protected/tenants/'
    | '/api/v1/entitlements/$tenantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiV1EntitlementsTenantIdRoute: typeof ApiV1EntitlementsTenantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit': {
      id: '/_protected/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ProtectedAuditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/flags': {
      id: '/_protected/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof ProtectedFlagsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services': {
      id: '/_protected/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ProtectedServicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/subscriptions': {
      id: '/_protected/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof ProtectedSubscriptionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tenants/': {
      id: '/_protected/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof ProtectedTenantsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tenants/$id': {
      id: '/_protected/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof ProtectedTenantsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entitlements/$tenantId': {
      id: '/api/v1/entitlements/$tenantId'
      path: '/api/v1/entitlements/$tenantId'
      fullPath: '/api/v1/entitlements/$tenantId'
      preLoaderRoute: typeof ApiV1EntitlementsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAuditRoute: typeof ProtectedAuditRoute
  ProtectedFlagsRoute: typeof ProtectedFlagsRoute
  ProtectedServicesRoute: typeof ProtectedServicesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSubscriptionsRoute: typeof ProtectedSubscriptionsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTenantsIdRoute: typeof ProtectedTenantsIdRoute
  ProtectedTenantsIndexRoute: typeof ProtectedTenantsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAuditRoute: ProtectedAuditRoute,
  ProtectedFlagsRoute: ProtectedFlagsRoute,
  ProtectedServicesRoute: ProtectedServicesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSubscriptionsRoute: ProtectedSubscriptionsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTenantsIdRoute: ProtectedTenantsIdRoute,
  ProtectedTenantsIndexRoute: ProtectedTenantsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiV1EntitlementsTenantIdRoute: ApiV1EntitlementsTenantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
